user root;
worker_processes auto;
error_log /logs/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    access_log /logs/access.log;
    
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    
    server {
        listen 80 default_server reuseport;
        listen [::]:80 default_server reuseport;
        
        server_name _;
        root /www;
        
        location / {
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
            
            types {
                application/octet-stream *;
            }
            
            client_max_body_size 0;
            allow all;
        }
    }
}